version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=abc123.
      - MYSQL_DATABASE=recetario
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
  jenkins:
    image: jenkins/jenkins:lts
    ports: 
      - '8090:8080'
    volumes:
      - jenkins-cfg:/var/jenkins_home
volumes:
  dbdata:
  jenkins-cfg: