version: '3.8'

services:
  db:
    container_name: recetario-db
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=abc123.
      - MYSQL_DATABASE=recetario
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
  
  app:
    container_name: recetario-server
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://recetario-db:3306/recetario
    depends_on:
      - db

volumes:
  dbdata:
